# Generated by Django 4.0 on 2022-01-23 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(default='')),
                ('option_1', models.CharField(default='', max_length=200)),
                ('option_2', models.CharField(default='', max_length=200)),
                ('option_3', models.CharField(default='', max_length=200)),
                ('option_4', models.CharField(default='', max_length=200)),
                ('correct_option', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('category_name', models.CharField(default='', max_length=40)),
                ('instructions', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('student_name', models.CharField(default='', max_length=50)),
                ('submission_token', models.CharField(default='91921cbe-92d7-45e4-b4b7-009c81fe64ee', max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.quiz'),
        ),
    ]
