# Generated by Django 4.0 on 2021-12-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_delete_answer_delete_question_quiz_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='wrong_choice',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.question')),
            ],
        ),
    ]
