# Generated by Django 4.0 on 2021-12-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_remove_quiz_correct_answer_remove_quiz_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
