# Generated by Django 4.0 on 2021-12-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.answer')),
            ],
        ),
    ]
