# Generated by Django 4.0 on 2022-01-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_answer_is_correct_quiz_instructions_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='option_A',
        ),
        migrations.AddField(
            model_name='answer',
            name='option_B',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_C',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_D',
            field=models.CharField(default='', max_length=200),
        ),
    ]
