# Generated by Django 4.0 on 2022-01-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_questionresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='quiz',
        ),
    ]
