# Generated by Django 4.0 on 2022-01-12 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_remove_questionresponse_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='submission_token',
            field=models.CharField(default=uuid.UUID('95515796-60e8-4f92-9b44-1a9c6697609a'), max_length=255),
        ),
    ]
