# Generated by Django 4.0 on 2022-01-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_questionresponse_submission_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_app.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='submission_token',
            field=models.CharField(default='92a362c4-a50a-45df-8ee8-7d0cc58da484', max_length=255),
        ),
    ]
