# Generated by Django 4.0 on 2022-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_questionresponse_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='submission_token',
            field=models.CharField(default='26b6c73a-d2b4-4f1e-8242-bd9d9e56aba1', max_length=255),
        ),
    ]
