# Generated by Django 4.0 on 2022-01-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_alter_questionresponse_submission_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='submission_token',
            field=models.CharField(default='8ab2a5b2-c9f9-47a0-9493-26693d883cdf', max_length=255),
        ),
    ]
