# Generated by Django 4.0 on 2022-01-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_alter_questionresponse_submission_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='submission_token',
            field=models.CharField(default='248e7923-5112-4c9f-b427-9f2422b30877', max_length=255),
        ),
    ]
